# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T:\Han\scriptBk\shotgun_api3\apiUi.ui'
#
# Created: Thu Jun 23 17:21:58 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(306, 277)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 10, 291, 91))
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtGui.QWidget()
        self.page.setObjectName("page")
        self.userImg = QtGui.QPushButton(self.page)
        self.userImg.setGeometry(QtCore.QRect(20, 10, 64, 64))
        self.userImg.setText("")
        self.userImg.setIconSize(QtCore.QSize(64, 64))
        self.userImg.setFlat(True)
        self.userImg.setObjectName("userImg")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName("page_2")
        self.lineEdit = QtGui.QLineEdit(self.page_2)
        self.lineEdit.setGeometry(QtCore.QRect(120, 40, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtGui.QLineEdit(self.page_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 10, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.stackedWidget.addWidget(self.page_2)
        self.Project = QtGui.QFrame(self.centralwidget)
        self.Project.setGeometry(QtCore.QRect(0, 110, 301, 141))
        self.Project.setFrameShape(QtGui.QFrame.NoFrame)
        self.Project.setFrameShadow(QtGui.QFrame.Plain)
        self.Project.setObjectName("Project")
        self.cB_project = QtGui.QComboBox(self.Project)
        self.cB_project.setGeometry(QtCore.QRect(50, 10, 241, 22))
        self.cB_project.setObjectName("cB_project")
        self.lb_project = QtGui.QLabel(self.Project)
        self.lb_project.setGeometry(QtCore.QRect(10, 10, 41, 16))
        self.lb_project.setObjectName("lb_project")
        self.cB_type = QtGui.QComboBox(self.Project)
        self.cB_type.setGeometry(QtCore.QRect(50, 40, 91, 22))
        self.cB_type.setObjectName("cB_type")
        self.lb_seq = QtGui.QLabel(self.Project)
        self.lb_seq.setGeometry(QtCore.QRect(150, 40, 51, 20))
        self.lb_seq.setObjectName("lb_seq")
        self.lb_shot = QtGui.QLabel(self.Project)
        self.lb_shot.setGeometry(QtCore.QRect(10, 80, 31, 20))
        self.lb_shot.setObjectName("lb_shot")
        self.cB_shot = QtGui.QComboBox(self.Project)
        self.cB_shot.setGeometry(QtCore.QRect(50, 80, 91, 22))
        self.cB_shot.setObjectName("cB_shot")
        self.lb_task = QtGui.QLabel(self.Project)
        self.lb_task.setGeometry(QtCore.QRect(160, 80, 31, 20))
        self.lb_task.setObjectName("lb_task")
        self.cB_task = QtGui.QComboBox(self.Project)
        self.cB_task.setGeometry(QtCore.QRect(200, 80, 91, 22))
        self.cB_task.setObjectName("cB_task")
        self.lb_type = QtGui.QLabel(self.Project)
        self.lb_type.setGeometry(QtCore.QRect(10, 40, 51, 20))
        self.lb_type.setObjectName("lb_type")
        self.cB_seq = QtGui.QComboBox(self.Project)
        self.cB_seq.setGeometry(QtCore.QRect(200, 40, 91, 22))
        self.cB_seq.setObjectName("cB_seq")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 306, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_project.setText(QtGui.QApplication.translate("MainWindow", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_seq.setText(QtGui.QApplication.translate("MainWindow", "Sequence", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_shot.setText(QtGui.QApplication.translate("MainWindow", "Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_task.setText(QtGui.QApplication.translate("MainWindow", "Task", None, QtGui.QApplication.UnicodeUTF8))
        self.lb_type.setText(QtGui.QApplication.translate("MainWindow", "Type", None, QtGui.QApplication.UnicodeUTF8))

