# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T:\Han\scriptBk\deformerOnMesh\ui_DeformerOnMesh\ui_DeformerOnMesh.ui'
#
# Created: Fri Jun 09 17:54:04 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(209, 413)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setAttribute(QtCore.Qt.WA_DeleteOnClose, True) 
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_run = QtGui.QPushButton(self.frame)
        self.btn_run.setGeometry(QtCore.QRect(0, 260, 191, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_run.sizePolicy().hasHeightForWidth())
        self.btn_run.setSizePolicy(sizePolicy)
        self.btn_run.setObjectName("btn_run")
        self.btn_remove = QtGui.QPushButton(self.frame)
        self.btn_remove.setGeometry(QtCore.QRect(0, 330, 191, 23))
        self.btn_remove.setObjectName("btn_remove")
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 220, 191, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, 310, 191, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.btn_mesh = QtGui.QPushButton(self.frame)
        self.btn_mesh.setGeometry(QtCore.QRect(100, 90, 91, 23))
        self.btn_mesh.setObjectName("btn_mesh")
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.label.setObjectName("label")
        self.cB_forceNew = QtGui.QCheckBox(self.frame)
        self.cB_forceNew.setGeometry(QtCore.QRect(90, 240, 101, 17))
        self.cB_forceNew.setObjectName("cB_forceNew")
        self.btn_follicle = QtGui.QPushButton(self.frame)
        self.btn_follicle.setGeometry(QtCore.QRect(0, 90, 91, 23))
        self.btn_follicle.setObjectName("btn_follicle")
        self.cB_default = QtGui.QCheckBox(self.frame)
        self.cB_default.setGeometry(QtCore.QRect(10, 240, 81, 17))
        self.cB_default.setObjectName("cB_default")
        self.btn_ctrl = QtGui.QPushButton(self.frame)
        self.btn_ctrl.setGeometry(QtCore.QRect(0, 60, 91, 23))
        self.btn_ctrl.setObjectName("btn_ctrl")
        self.hS_falloff = QtGui.QSlider(self.frame)
        self.hS_falloff.setGeometry(QtCore.QRect(0, 195, 191, 21))
        self.hS_falloff.setMaximum(1000)
        self.hS_falloff.setSingleStep(0)
        self.hS_falloff.setSliderPosition(4)
        self.hS_falloff.setOrientation(QtCore.Qt.Horizontal)
        self.hS_falloff.setTickPosition(QtGui.QSlider.TicksAbove)
        self.hS_falloff.setTickInterval(100)
        self.hS_falloff.setObjectName("hS_falloff")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 31, 16))
        self.label_2.setObjectName("label_2")
        self.btn_reset = QtGui.QPushButton(self.frame)
        self.btn_reset.setGeometry(QtCore.QRect(100, 60, 91, 23))
        self.btn_reset.setObjectName("btn_reset")
        self.btn_next = QtGui.QPushButton(self.frame)
        self.btn_next.setGeometry(QtCore.QRect(130, 30, 61, 23))
        self.btn_next.setObjectName("btn_next")
        self.btn_last = QtGui.QPushButton(self.frame)
        self.btn_last.setGeometry(QtCore.QRect(60, 30, 61, 23))
        self.btn_last.setObjectName("btn_last")
        self.btn_member = QtGui.QPushButton(self.frame)
        self.btn_member.setGeometry(QtCore.QRect(0, 140, 91, 23))
        self.btn_member.setObjectName("btn_member")
        self.btn_falloff = QtGui.QPushButton(self.frame)
        self.btn_falloff.setGeometry(QtCore.QRect(100, 140, 91, 23))
        self.btn_falloff.setObjectName("btn_falloff")
        self.dSB_falloff = QtGui.QDoubleSpinBox(self.frame)
        self.dSB_falloff.setGeometry(QtCore.QRect(51, 170, 141, 22))
        self.dSB_falloff.setObjectName("dSB_falloff")
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(0, 120, 191, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.lV_selection = QtGui.QListView(self.frame)
        self.lV_selection.setGeometry(QtCore.QRect(60, 5, 131, 21))
        self.lV_selection.setAutoScroll(False)
        self.lV_selection.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.lV_selection.setObjectName("lV_selection")
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 209, 17))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Defomer on Surface", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_run.setText(QtGui.QApplication.translate("MainWindow", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_remove.setText(QtGui.QApplication.translate("MainWindow", "Remove Deformer", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_mesh.setText(QtGui.QApplication.translate("MainWindow", "Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.cB_forceNew.setText(QtGui.QApplication.translate("MainWindow", "Force New", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_follicle.setText(QtGui.QApplication.translate("MainWindow", "Follicle", None, QtGui.QApplication.UnicodeUTF8))
        self.cB_default.setText(QtGui.QApplication.translate("MainWindow", "Use Default", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ctrl.setText(QtGui.QApplication.translate("MainWindow", "Ctrl", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Falloff", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_reset.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_next.setText(QtGui.QApplication.translate("MainWindow", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_last.setText(QtGui.QApplication.translate("MainWindow", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_member.setText(QtGui.QApplication.translate("MainWindow", "Member Set", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_falloff.setText(QtGui.QApplication.translate("MainWindow", "Falloff", None, QtGui.QApplication.UnicodeUTF8))

